apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: library-management
data:
  NODE_ENV: "production"
  MONGODB_URI: "mongodb://mongodb:27017/library_management"
  BACKEND_PORT: "5000"
