apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: library-management
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin123"
  MONGODB_URI: "mongodb://admin:admin123@mongodb:27017/library_management?authSource=admin"
